[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.3.1"
  export = ["feb16_greeting_service"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/RestApi","Category/Service","Internal/http"]
  name = "feb16_greeting_service"
  org = "lakshansivagnanasothy"
  version = "3.1.0"

